controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

auth_login:
  path: /api/auth/login
  methods: [POST]

auth_refresh:
  path: /api/auth/refresh
  methods: [POST]
  controller: gesdinet.jwtrefreshtoken::refresh

auth_logout:
  path: /api/auth/logout
  methods: [POST]
